#!/usr/bin/env bash

# Color styling.
getColorCode() {
    tput "$@" 2>/dev/null || true
}

COLOR_NORMAL=$(getColorCode sgr0)
COLOR_BLACK=$(getColorCode setaf 0)
COLOR_RED=$(getColorCode setaf 1)
COLOR_GREEN=$(getColorCode setaf 2)
COLOR_YELLOW=$(getColorCode setaf 3)
COLOR_BLUE=$(getColorCode setaf 4)
COLOR_MAGENTA=$(getColorCode setaf 5)
COLOR_CYAN=$(getColorCode setaf 6)
COLOR_WHITE=$(getColorCode setaf 7)

TEXT_BOLD=$(getColorCode bold)

##
# startProj
#
    echo
    echo -e "${COLOR_GREEN}""Starting project.""${COLOR_NORMAL}"

    PROJ="${1:-build}"
    if [ ! "$PROJ" == "$1" ]; then
        echo
        echo -e "${COLOR_YELLOW}""   Assumes project as :"\
            "$PROJ""${COLOR_NORMAL}"
    fi

    echo
    if cmake --help | grep -qi 'Ninja'; then
        echo -e "${COLOR_BLUE}""-- Using Ninja generator"\
            "for faster build.""${COLOR_NORMAL}"
        rm -rf "$PROJ" && cmake -B "$PROJ" -S . -G Ninja
        RESULT=$?
    else
        echo -e "${COLOR_YELLOW}""-- Un-available Ninja generator,"\
            "build is slower.""${COLOR_NORMAL}"
        rm -rf "$PROJ" && cmake -B "$PROJ" -S .
        RESULT=$?
    fi

    echo
    echo -e "${COLOR_GREEN}""Project started.""${COLOR_NORMAL}"
    exit "$RESULT"
